name: "S1 Zone editor"
description: "Add-on for creating and tuning detection zones, live tracking, and heatmap visualization for Sensy-One devices."
version: "v1.3.7"
slug: "sensy_one_device_finder"
init: false
arch:
  - aarch64
  - amd64
startup: services
boot: auto
ingress: true
ingress_port: 8099
panel_title: "S1 Zone editor"
panel_icon: "mdi:vector-polygon"
homeassistant_api: true
